env = Environment(
	CCFLAGS = [ '-Isrc', '-Lsrc', '-std=c99'],
	LIBPATH = ['#/src'],
	LIBS = ['cq_irc_client', 'stdc++', 'boost_system', 'pthread'])

if int(ARGUMENTS.get('debug', 1)) == True:
	env.Append(CCFLAGS = ['-g', '-Wall'])
else:
	env.Append(CCFLAGS = ['-Wall', '-O2'])

env.Program('test1', 'test1.c')